global_id_user = None
sensor_counts = {}
global_id_config = None
global_sensor_entries = []
global_scenario_name_configuration = None
global_description_configuration = None
global_id_config_selectionned=None
global_new_id_observation=None
global_connected_admin_login=None
global_connected_admin_password=None
